### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by elypma** [kata198/VirtualEnvOnDemand#1]
Would it be possible to provide windows support "out-of-the-box"?
I managed to get it working with a few hacks but I'm not sure if I have overlooked something.

[VirtualEnvOnDemand.zip](https://github.com/kata198/VirtualEnvOnDemand/files/614753/VirtualEnvOnDemand.zip)
.

**Comment by kata198** [comment]
Sorry I missed your message! 

Yes, it should be able to work on windows. I have tested and it does currently work through cygwin ( www.cygwin.com ) .

What issues are you having? Can you please do the following:

1. Fork VirtualEnvOnDemand under your account
2. Commit your changes
3. Open a pull request of your changes

and I'll overview them.

Thanks,
Tim

**Comment by kata198** [comment]
Doing a diff of your changes, I note the following there are many issues. 

Give me a couple moments, I've installed virtualenv / virtalenvondemand on a windows VM. I will make it compatible and release the update.

**Comment by kata198** [comment]
Alrighty, I've made all the changes to make it both Windows, Linux, Cygwin, Unix, Mac, etc, compatible.

I was not aware that virtualenv would use different paths altogether in created environments on windows, but I guess that's the windows way: Break compatibility for no reason at all.

Thanks for identifying that there was an issue, apparently my cygwin testing alone was not enough. I did not end up using any of your code -- since your code just hacked it to work on Windows alone and break on Linux, Cygwin, and all the rest.

I did however credit you in the commit log and the ChangeLog. Thanks, and enjoy version 6.0.0!
